### PR TITLE
Update user.py

### PR DESCRIPTION
**Pull request by parsa-rahbari-82**
Some improvement. Use "cls" instead of the class name. unnecessary "cls" argument removed in "add_book" method.

### CODE REVIEW

**Review by PEMIDI — APPROVED** [review]
Thank you :)

**Comment by PEMIDI** [comment]
I reviewed your code and merged it into the project.

**Comment by PEMIDI** [comment]
> I reviewed your code and merged it into the project.

@parsa-rahbari-82

**Comment by parsa-rahbari-82** [comment]
> Thank you :)

Your welcome.

**Pull request merged**
